import json, sys, os
sys.path.insert(0, os.environ["UNIT"]); os.chdir(os.environ["UNIT"])
import torch, unit as U
contract = json.load(open("contract.json"))
case = next(c for c in contract["cases"] if c["id"] == "single_chunk_bd1")
inputs = U.make_inputs(case)
ref = U.reference_stages(inputs)
opts = {"device": "a2", "backend": "cce", "block_dim": 1, "launcher": os.environ["LAUNCHER"],
        "timeout": 1800, "board": None, "out_dir": os.environ["OUT"]}
got = U.execute_stages(inputs, opts)
torch.set_printoptions(precision=5, sci_mode=False, linewidth=200)
g, r = got["inverse_dainv.D_tri"][0,0,0].float(), ref["inverse_dainv.D_tri"][0,0,0].float()
beta = inputs["beta"][0,:,0].float()
print("beta[:6]", beta[:6].tolist())
print("ref row3 [:5]", r[3,:5].tolist())
print("got row3 [:5]", g[3,:5].tolist())
ratio = (g[3,:3] / r[3,:3])
print("got/ref row3 [:3]", ratio.tolist())
print("beta[:3]", beta[:3].tolist(), " beta[3]", float(beta[3]))
print("ratio*beta[col]", (ratio * beta[:3]).tolist())
nz = (g - r).abs()
print("nonzero-diff count", int((nz > 1e-6).sum()), "of", nz.numel())
rows = sorted(set(torch.nonzero(nz > 1e-6)[:,0].tolist()))
cols = sorted(set(torch.nonzero(nz > 1e-6)[:,1].tolist()))
print("rows with diff:", rows[:12], "...")
print("cols with diff:", cols[:12], "...")
dv = got["inverse_epilogue.dv"][0,:,0].float(); dvr = ref["inverse_epilogue.dv"][0,:,0].float()
print("dv nan count", int(torch.isnan(dv).sum()), "of", dv.numel())
print("dv ref[0,:4]", dvr[0,:4].tolist()); print("dv got[0,:4]", dv[0,:4].tolist())
dvb = ref["inverse_mm.d_v_beta"][0,0,0].float()
print("d_v_beta[0,:4]", dvb[0,:4].tolist(), "beta0", float(beta[0]))
